export enum DISPATCH_TYPES  {
    CATEGORY = "DISPATCH_CATEGORY",
    TODO = "DISPATCH_TODO",
    LOCAL_TODO = "DISPATCH_LOCAL_TODO",
    LOCAL_CATEGORY = "DISPATCH_LOCAL_CATEGORY",
    LOCAL_TOTAL_DATA = "DISPATCH_LOCAL_TOTAL_DATA",
}